channel_priority:
  - strict

# Required to continue building python 3.9
python:
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.12.* *_cpython
  - 3.13.* *_cp313
is_python_min:
  - true
  - false
  - false
  - false
  - false
